[default.vcr]
# tapes_folder = "/run/media/allie/Voyager/data/vhs_tapes"
# feed_tape = "/run/media/allie/Voyager/data/vhs_tapes/feed.vhs"
# site_tape = "/run/media/allie/Voyager/data/vhs_tapes/site_assets.vhs"