[default.vcr]
entities_cache_size = 100
tapes = "./tapes/"
site_assets = "./tapes/site_data/"
zstd_dictionaries = "./zstd-dictionaries/" # this is optional; you can exclude it if your dataset doesn't require dicts.
cors = true
time_responses = true
open_in_browser = false
parallelize_stream_data = false # make stream data fetching parallel
gui = true

# if you don't want to include feed support, just comment this bit out!
[default.vcr.feed]
index = "./tapes/feed/feed.fp"
path = "./tapes/feed/feed.riv"
dict = "./zstd-dictionaries/feed.dict"
id_table = "./tapes/feed/id_lookup.bin"
tag_table = "./tapes/feed/tag_indexes.fp"
cache_size = 50
