[package]
name = "player"
version = "0.1.0"
edition = "2021"

[features]
bundle_before = ["before", "open"]

[dependencies]
lru = "0.6.6"
rand = "0.8.4"
uuid = "0.8.2"
rayon = "1.5.1"

[dependencies.blaseball_vcr]
path = "../vcr_lib"

[dependencies.before]
git = "https://github.com/iliana/before.git"
branch = "main"
optional = true
default-features = false

[dependencies.rocket]
version = "0.5.0-rc.1"
features = ["json"]

[dependencies.chrono]
version = "0.4"
features = ["serde"]

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.open]
version = "2"
optional = true

[dependencies.serde_json]
version = "1.0.64"
features = ["preserve_order", "raw_value"]

[[bin]]
name = "player"
path = "src/server.rs"
